# Enable/Disable Built-In Features
aha_board: false
question_board: false


# Custom Sidebar Links to External Sites.
# ----------------------------------------
# Must be an array.  Start with a dash on its own line.
# Then indent and provide label, url, and fa icon (optional)
# The default icon is fa-cloud.
sidebar:
  
  -
    label: Syllabus
    url: 'https://github.com/GoLearnToCode/kiei925-spring16/blob/master/files/KIEI-925-0-81_Spring2016.pdf'
    icon: fa-list-ol
  - 
    label: Discussion
    url: "https://canvas.northwestern.edu/courses/38522/discussion_topics"
    icon: fa-comments
  - 
    label: Grades
    url: "https://canvas.northwestern.edu/courses/38522/gradebook"
    icon: fa-star-o
  
